In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel('/content/drive/MyDrive/Colab/DryBeanDataset/Dry_Bean.xlsx')

print(df)

        Area  Perimeter  MajorAxisLength  ...  ShapeFactor3  ShapeFactor4  Class
0      28395    610.291       208.178117  ...      0.834222      0.998724      0
1      28734    638.018       200.524796  ...      0.909851      0.998430      0
2      29380    624.110       212.826130  ...      0.825871      0.999066      0
3      30008    645.884       210.557999  ...      0.861794      0.994199      0
4      30140    620.134       201.847882  ...      0.941900      0.999166      0
...      ...        ...              ...  ...           ...           ...    ...
13606  42097    759.696       288.721612  ...      0.642988      0.998385      6
13607  42101    757.499       281.576392  ...      0.676099      0.998219      6
13608  42139    759.321       281.539928  ...      0.676884      0.996767      6
13609  42147    763.779       283.382636  ...      0.668237      0.995222      6
13610  42159    772.237       295.142741  ...      0.616221      0.998180      6

[13611 rows x 17 columns]


In [ ]:
dataset = df.values
print(dataset)

[[2.83950000e+04 6.10291000e+02 2.08178117e+02 ... 8.34222388e-01
  9.98723889e-01 0.00000000e+00]
 [2.87340000e+04 6.38018000e+02 2.00524796e+02 ... 9.09850506e-01
  9.98430331e-01 0.00000000e+00]
 [2.93800000e+04 6.24110000e+02 2.12826130e+02 ... 8.25870617e-01
  9.99066137e-01 0.00000000e+00]
 ...
 [4.21390000e+04 7.59321000e+02 2.81539928e+02 ... 6.76884164e-01
  9.96767264e-01 6.00000000e+00]
 [4.21470000e+04 7.63779000e+02 2.83382636e+02 ... 6.68236684e-01
  9.95222420e-01 6.00000000e+00]
 [4.21590000e+04 7.72237000e+02 2.95142741e+02 ... 6.16220592e-01
  9.98179623e-01 6.00000000e+00]]


In [ ]:
X = dataset[:,0:16]
X -= X.mean(axis=0)
X /= X.std(axis=0)
print(X)

[[-0.84074853 -1.1433189  -1.30659814 ...  2.40217287  1.92572347
   0.83837103]
 [-0.82918764 -1.01392388 -1.39591111 ...  3.10089314  2.68970162
   0.77113842]
 [-0.80715717 -1.07882906 -1.25235661 ...  2.23509147  1.84135576
   0.91675514]
 ...
 [-0.37203825 -0.44783294 -0.45047814 ...  0.28920441  0.33632829
   0.39025114]
 [-0.37176543 -0.42702856 -0.42897404 ...  0.22837538  0.2489734
   0.03644001]
 [-0.37135619 -0.38755718 -0.2917356  ... -0.12777587 -0.2764814
   0.71371948]]


In [ ]:
Y = dataset[:,16]
print(Y)

[0. 0. 0. ... 6. 6. 6.]


In [ ]:
#@title

'''
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
print(X_scale)
'''

In [ ]:
from sklearn.model_selection import train_test_split


# 選取自變數資料 
#data = Y[:, :17] 
data = X

# 選取因變數資料 
#target = dataset['Class'] 
target = Y


# 使用scikit-learn將資料集劃分為訓練集和測試集 
train_data, test_data, train_target, test_target = train_test_split(data, target, test_size=0.2, train_size=0.8) 


'''
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.2)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.2)
#print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)
print(X_val,Y_val)
'''

'\nX_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.2)\nX_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.2)\n#print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)\nprint(X_val,Y_val)\n'

In [ ]:
import numpy as np
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
import numpy as np
import keras
from keras.utils import np_utils
from tensorflow.python.keras import regularizers
import matplotlib.pyplot as plt
x_train = train_data
y_train = train_target
x_test = test_data
y_test = test_target

'''
model = Sequential()
model.add(Dense(16, input_shape=(16,), activation="relu"))
model.add(Dense(16, activation="relu"))
model.add(Dense(7, activation="softmax"))

model.compile(loss="sparse_categorical_crossentropy", optimizer="adam",
metrics=["accuracy"])

model.fit(x_train, y_train, epochs=20, batch_size=10, verbose=1)
'''



model = Sequential()

model.add(Dense(16, activation='relu'))

model.add(Dense(32, activation='relu'))

model.add(Dense(64, activation='relu'))



#keras.regularizers.l1(0.01)
#keras.regularizers.l2(0.01)
#keras.regularizers.l1_l2(l2=0.01)
#model.add(Dropout(0.5))
model.add(Dense(7, activation='softmax',))
#adm = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='sparse_categorical_crossentropy',
optimizer='adam',
metrics=['accuracy'])
model.fit(x_train, y_train,
epochs=25,
batch_size=100)
score = model.evaluate(x_test, y_test,batch_size=100)




Epoch 1/25
109/109 [==============================] - 3s 3ms/step - loss: 1.4612 - accuracy: 0.5564
Epoch 2/25
109/109 [==============================] - 0s 3ms/step - loss: 0.4163 - accuracy: 0.8607
Epoch 3/25
109/109 [==============================] - 0s 2ms/step - loss: 0.2580 - accuracy: 0.9098
Epoch 4/25
109/109 [==============================] - 0s 3ms/step - loss: 0.2176 - accuracy: 0.9239
Epoch 5/25
109/109 [==============================] - 0s 3ms/step - loss: 0.2099 - accuracy: 0.9279
Epoch 6/25
109/109 [==============================] - 0s 3ms/step - loss: 0.1937 - accuracy: 0.9297
Epoch 7/25
109/109 [==============================] - 0s 3ms/step - loss: 0.1999 - accuracy: 0.9268
Epoch 8/25
109/109 [==============================] - 0s 3ms/step - loss: 0.2013 - accuracy: 0.9276
Epoch 9/25
109/109 [==============================] - 0s 3ms/step - loss: 0.1944 - accuracy: 0.9270
Epoch 10/25
109/109 [==============================] - 0s 3ms/step - loss: 0.1898 - accuracy: 0.9327

In [ ]:
loss, accuracy = model.evaluate(train_data, train_target)
print("訓練資料集的準確度 = {:.4f}".format(accuracy))
loss, accuracy = model.evaluate(test_data, test_target)
print("測試資料集的準確度 = {:.4f}".format(accuracy))
print("_______")
print(train_test_split)

341/341 [==============================] - 1s 2ms/step - loss: 0.1786 - accuracy: 0.9352
訓練資料集的準確度 = 0.9352
86/86 [==============================] - 0s 2ms/step - loss: 0.2074 - accuracy: 0.9254
測試資料集的準確度 = 0.9254
_______
<function train_test_split at 0x7f1d3768a710>


In [ ]:
import numpy as np
import pandas as pd
import math
import scipy.stats as sci
from sklearn.model_selection import train_test_split
from sklearn import ensemble, metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

forest = ensemble.RandomForestClassifier(n_estimators=1000)
forest_fit = forest.fit(x_train, y_train)
test_y_predicted = forest.predict(x_test)
accuracy = metrics.accuracy_score(y_test, test_y_predicted)
C = confusion_matrix(y_test, test_y_predicted)
print("Score",forest.score(x_test, y_test))
print(accuracy)
print(C)
print(classification_report(y_test, test_y_predicted))

Score 0.9203084832904884
0.9203084832904884
[[366   1   0   0   0   8   8]
 [  1 230   1  17   3   9   0]
 [  0   0  93   0   0   0   0]
 [  0  11   0 314   6   0   0]
 [  0   1   0   6 387   7   2]
 [  7   3   0   0  11 483  59]
 [ 12   0   0   0   2  42 633]]
              precision    recall  f1-score   support

         0.0       0.95      0.96      0.95       383
         1.0       0.93      0.88      0.91       261
         2.0       0.99      1.00      0.99        93
         3.0       0.93      0.95      0.94       331
         4.0       0.95      0.96      0.95       403
         5.0       0.88      0.86      0.87       563
         6.0       0.90      0.92      0.91       689

    accuracy                           0.92      2723
   macro avg       0.93      0.93      0.93      2723
weighted avg       0.92      0.92      0.92      2723



In [ ]:
#@title
'''NO'''
from sklearn import metrics 

train_predict = model.predict(train_data) 
test_predict = model.predict(test_data) 

train_proba = model.predict_proba(train_data)[:,6] 
test_proba = model.predict_proba(test_data)[:,6] 

#print(train_proba)

print(metrics.confusion_matrix(test_target, test_predict, labels=[0,1,2,3,4,5,6])) 
print(metrics.classification_report(test_target, test_predict)) 


In [ ]:
#@title
'''NO'''
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.preprocessing import label_binarize

# For each class
Y = label.classification(y, classes = [0,1,2,3,4,5,6])
n_classes = Y.shape[1]
precision = dict()
recall = dict()
average_precision = dict()
for i in range(n_classes):
    precision[i], recall[i], _ = precision_recall_curve(Y_test[:, i],
                                                        y_score[:, i])
    average_precision[i] = average_precision_score(Y_test[:, i], y_score[:, i])

# A "micro-average": quantifying score on all classes jointly
precision["micro"], recall["micro"], _ = precision_recall_curve(Y_test.ravel(),
    y_score.ravel())
average_precision["micro"] = average_precision_score(Y_test, y_score,
                                                     average="micro")
print('Average precision score, micro-averaged over all classes: {0:0.2f}'
      .format(average_precision["micro"]))


In [ ]:
#@title
'''NO'''
# create confusion matrix
y_true = np.array([-1]*700 + [0]*700 + [1]*700 + [2]*700 + [3]*700 + [4]*700 +[5]*700)
y_pred = np.array([-1]*100 + [0]*100 + [1]*100 + [2]*100 + [3]*100 + [4]*100 + [5]*100 +
            [-1]*100 + [0]*100 + [1]*100 + [2]*100 + [3]*100 + [4]*100 + [5]*100 +
              [-1]*100 + [0]*100 + [1]*100 + [2]*100 + [3]*100 + [4]*100 + [5]*100 +
                [-1]*100 + [0]*100 + [1]*100 + [2]*100 + [3]*100 + [4]*100 + [5]*100 +
                  [-1]*100 + [0]*100 + [1]*100 + [2]*100 + [3]*100 + [4]*100 + [5]*100 +
                    [-1]*100 + [0]*100 + [1]*100 + [2]*100 + [3]*100 + [4]*100 + [5]*100 +
                      [-1]*100 + [0]*100 + [1]*100 + [2]*100 + [3]*100 + [4]*100 + [5]*100)
cm = confusion_matrix(y_true, y_pred)
conf_matrix = pd.DataFrame(cm, index=[0,1,2,3,4,5,6], columns=[0,1,2,3,4,5,6])

# plot size setting
fig, ax = plt.subplots(figsize = (15,15))
sns.heatmap(conf_matrix, annot=True, annot_kws={"size": 19}, cmap="Blues")
plt.ylabel('True label', fontsize=18)
plt.xlabel('Predicted label', fontsize=18)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.savefig('confusion.pdf', bbox_inches='tight')
plt.show()

In [ ]:
#@title
'''NO'''
print('------Weighted------')
print('Weighted precision', precision_score(y_true, y_pred, average='weighted'))
print('Weighted recall', recall_score(y_true, y_pred, average='weighted'))
print('Weighted f1-score', f1_score(y_true, y_pred, average='weighted'))
print('------Macro------')
print('Macro precision', precision_score(y_true, y_pred, average='macro'))
print('Macro recall', recall_score(y_true, y_pred, average='macro'))
print('Macro f1-score', f1_score(y_true, y_pred, average='macro'))
print('------Micro------')
print('Micro precision', precision_score(y_true, y_pred, average='micro'))
print('Micro recall', recall_score(y_true, y_pred, average='micro'))
print('Micro f1-score', f1_score(y_true, y_pred, average='micro'))

In [ ]:
#@title
'''NO'''
from sklearn.metrics import f1_score, precision_score, recall_score

y_true=[0,1,2,3,4,5,6]
y_pred=[0,1,2,3,4,5,6]

f1 = f1_score( y_true, y_pred, average='macro' )
p = precision_score(y_true, y_pred, average='macro')
r = recall_score(y_true, y_pred, average='macro')

print(f1, p, r)

數值型

In [ ]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
#np.random.seed(7)  # 指定亂數種子

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Colab/DryBeanDataset/Dry_Bean.xlsx')
dataset = df
#np.random.shuffle(dataset)  # 使用亂數打亂資料

print(dataset)

        Area  Perimeter  MajorAxisLength  ...  ShapeFactor3  ShapeFactor4  Class
0      28395    610.291       208.178117  ...      0.834222      0.998724      0
1      28734    638.018       200.524796  ...      0.909851      0.998430      0
2      29380    624.110       212.826130  ...      0.825871      0.999066      0
3      30008    645.884       210.557999  ...      0.861794      0.994199      0
4      30140    620.134       201.847882  ...      0.941900      0.999166      0
...      ...        ...              ...  ...           ...           ...    ...
13606  42097    759.696       288.721612  ...      0.642988      0.998385      6
13607  42101    757.499       281.576392  ...      0.676099      0.998219      6
13608  42139    759.321       281.539928  ...      0.676884      0.996767      6
13609  42147    763.779       283.382636  ...      0.668237      0.995222      6
13610  42159    772.237       295.142741  ...      0.616221      0.998180      6

[13611 rows x 17 columns]


In [ ]:
X = dataset.iloc[:, 0:15]
Y = dataset.iloc[:, 15]
print(X)
print(Y)

        Area  Perimeter  ...  ShapeFactor2  ShapeFactor3
0      28395    610.291  ...      0.003147      0.834222
1      28734    638.018  ...      0.003564      0.909851
2      29380    624.110  ...      0.003048      0.825871
3      30008    645.884  ...      0.003215      0.861794
4      30140    620.134  ...      0.003665      0.941900
...      ...        ...  ...           ...           ...
13606  42097    759.696  ...      0.001749      0.642988
13607  42101    757.499  ...      0.001886      0.676099
13608  42139    759.321  ...      0.001888      0.676884
13609  42147    763.779  ...      0.001852      0.668237
13610  42159    772.237  ...      0.001640      0.616221

[13611 rows x 15 columns]
0        0.998724
1        0.998430
2        0.999066
3        0.994199
4        0.999166
           ...   
13606    0.998385
13607    0.998219
13608    0.996767
13609    0.995222
13610    0.998180
Name: ShapeFactor4, Length: 13611, dtype: float64


In [ ]:
X -= X.mean(axis=0)
X /= X.std(axis=0)

In [ ]:
from sklearn.model_selection import train_test_split


# 選取自變數資料 

data = X

# 選取因變數資料 

target = Y


# 使用scikit-learn將資料集劃分為訓練集和測試集 
train_data, test_data, train_target, test_target = train_test_split(data, target, test_size=0.2, train_size=0.8, random_state = 10) 



In [ ]:
#@title
'''NO'''
# 构建一个顺序模型
model = Sequential()

# 在模型中添加一个全连接层
# 神经网络结构：1-10-1，即输入层为1个神经元，隐藏层10个神经元，输出层1个神经元。 

# 激活函数加法1
model.add(Dense(units=10, input_dim=1))
model.add(activation = 'tanh')),
model.add(Dense(units=1))
model.add(activation = 'tanh')),

# 激活函数加法2
# model.add(Dense(units=10, input_dim=1, activation='relu'))
# model.add(Dense(units=1, activation='relu'))

# 定义优化算法
sgd = SGD(lr=0.3)
# sgd: Stochastic gradient descent,随机梯度下降法
# mse: Mean Squared Error, 均方误差
model.compile(optimizer=sgd, loss='mse')

# 进行训练
for step in range(3000):
    # 每次训练一个批次
    cost = model.train_on_batch(x_data, y_data)
    # 每500个batch打印一次cost值
    if step % 200 == 0:
        print('cost: ', cost)
# 打印权值和偏置值
W, b = model.layers[0].get_weights()
print('W：', W, ' b: ', b)
# 模型有几层
print(len(model.layers))

In [ ]:
import numpy as np
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
import numpy as np
import keras
from keras.utils import np_utils
from tensorflow.python.keras import regularizers
import matplotlib.pyplot as plt



'''
model = Sequential()

model.add(Dense(16, activation='tanh'))

model.add(Dense(32, activation='tanh'))

model.add(Dense(64, activation='tanh'))

model.add(Dense(128, activation='tanh'))


#keras.regularizers.l1(0.01)
#keras.regularizers.l2(0.01)
#keras.regularizers.l1_l2(l2=0.01)

model.add(Dense(1, activation='linear',))
#adm = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
#adam= keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
model.compile(loss='mse',
optimizer='adam')
metrics=["mae"])
'''

model = Sequential()
model.add(Dense(32, activation="tanh"))
model.add(Dense(32, activation="tanh"))
model.add(Dense(1))
# 編譯模型
model.compile(loss="mape", optimizer="adam",
metrics=["mape"])

mode2 = Sequential()
model.add(Dense(32, activation="tanh"))
model.add(Dense(32, activation="tanh"))
model.add(Dense(1))
# 編譯模型
mode2.compile(loss="mse", optimizer="adam",
metrics=["mse"])



model.fit(train_data, train_target,
epochs=10,
batch_size=10)
score = model.evaluate(test_data, test_target,batch_size=100)
model.summary()


mode2.fit(train_data, train_target,
epochs=10,
batch_size=10)
score = model.evaluate(test_data, test_target,batch_size=100)
model.summary()


Epoch 1/10
1089/1089 [==============================] - 4s 3ms/step - loss: 8.8279 - mape: 8.8279
Epoch 2/10
1089/1089 [==============================] - 3s 3ms/step - loss: 0.4011 - mape: 0.4011
Epoch 3/10
1089/1089 [==============================] - 3s 3ms/step - loss: 0.3710 - mape: 0.3710
Epoch 4/10
1089/1089 [==============================] - 3s 3ms/step - loss: 0.4316 - mape: 0.4316
Epoch 5/10
1089/1089 [==============================] - 3s 3ms/step - loss: 0.3772 - mape: 0.3772
Epoch 6/10
1089/1089 [==============================] - 3s 3ms/step - loss: 0.3545 - mape: 0.3545
Epoch 7/10
1089/1089 [==============================] - 3s 3ms/step - loss: 0.4013 - mape: 0.4013
Epoch 8/10
1089/1089 [==============================] - 3s 3ms/step - loss: 0.4190 - mape: 0.4190
Epoch 9/10
1089/1089 [==============================] - 3s 3ms/step - loss: 0.3397 - mape: 0.3397
Epoch 10/10
28/28 [==============================] - 0s 2ms/step - loss: 0.3818 - mape: 0.3818
Model: "sequential_3"
_

In [ ]:
import math
mape = model.evaluate(train_data, train_target)
print("MAPE: ", mape)

mse = mode2.evaluate(train_data, train_target)
print("MSE: ", mse)

r2 = mode2.evaluate(train_data, train_target)
np_r2 = np.array(r2)
rmse = np_r2**0.5
print("RMSE: ", rmse)

341/341 [==============================] - 1s 2ms/step - loss: 0.3759 - mape: 0.3759
MAPE:  [0.37589237093925476, 0.37589237093925476]
341/341 [==============================] - 1s 2ms/step - loss: 1.9855 - mse: 1.9855
MSE:  [1.9854813814163208, 1.9854813814163208]
341/341 [==============================] - 1s 2ms/step - loss: 1.9855 - mse: 1.9855
RMSE:  [1.40907111 1.40907111]


Adult Data Sets

In [ ]:
%tensorflow_version 2.x
%load_ext tensorboard
# ! pip install tensorflow-addons
import tensorflow as tf
#import tensorflow_addons as tfa
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import xgboost
from sklearn.metrics import make_scorer
from sklearn.metrics import roc_auc_score
from keras.utils import np_utils
import numpy as np
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
import numpy as np
import keras
from keras.utils import np_utils
from tensorflow.python.keras import regularizers
import matplotlib.pyplot as plt




In [ ]:
Train = pd.read_csv('/content/drive/MyDrive/Colab/DryBeanDataset/Train.csv')
Test = pd.read_csv('/content/drive/MyDrive/Colab/DryBeanDataset/Test.csv')
#df = pd.read_csv('/content/drive/MyDrive/Colab/DryBeanDataset/adult.csv')
Train_dataset = Train
Test_dataset = Test



In [ ]:
encoder = LabelEncoder()
Train_features = Train_dataset.columns.tolist()
for each in Train_features:
    Train_dataset[each] = encoder.fit_transform(Train_dataset[each])


Test_features = Test_dataset.columns.tolist()
for col in Test_features:
    Test_dataset[col] = encoder.fit_transform(Test_dataset[col])

In [ ]:
x_train = Train_dataset.iloc[:, 1:16].values  

y_train = Train_dataset.iloc[:, 0].values

x_test = Test_dataset.iloc[:, 1:16].values  

y_test = Test_dataset.iloc[:, 0].values

In [ ]:
#@title
#encoder = LabelEncoder()
#encoder.fit(y_train)
#encoded_y_train = encoder.transform(y_train)
#dummy_yt = np_utils.to_categorical(encoded_y_train)


In [ ]:
#@title
#encoder = LabelEncoder()
#encoder.fit(y_test)
#encoded_y_test = encoder.transform(y_test)
#dummy_y = np_utils.to_categorical(encoded_y_test)

In [ ]:
print(x_train, x_test, y_train, y_test)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

[[   22     7  2671 ...    39    39     0]
 [   33     6  2926 ...    12    39     0]
 [   21     4 14086 ...    39    39     0]
 ...
 [   41     4  7883 ...    39    39     0]
 [    5     4 12881 ...    19    39     0]
 [   35     5 17825 ...    39    39     1]] [[    8     4  8931 ...    39    38     0]
 [   21     4  1888 ...    49    38     0]
 [   11     2 11540 ...    39    38     1]
 ...
 [   21     4 12014 ...    49    38     0]
 [   27     4  1718 ...    39    38     0]
 [   18     5  6520 ...    59    38     1]] [ 9  9 11 ... 11 11 11] [ 1 11  7 ...  9  9  9]
(32561, 14) (16281, 14) (32561,) (16281,)


In [ ]:
import keras 
from keras.models import Sequential,Input,Model
from keras.layers import Dense,Dropout,Activation,Flatten
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam
from keras import initializers

In [ ]:
import numpy as np
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
import numpy as np
import keras
from keras.utils import np_utils
from tensorflow.python.keras import regularizers
import matplotlib.pyplot as plt



model = Sequential()
model.add(Dense(1024, activation="relu"))
model.add(Dense(2048, activation="relu"))

model.add(Dense(16, activation= 'softmax'))
# 編譯模型
model.compile(loss='sparse_categorical_crossentropy', optimizer="adam",
metrics=["accuracy"])


model.fit(x_train, y_train,
epochs=30,
batch_size=50)
score = model.evaluate(x_test, y_test,batch_size=10)
model.summary()
'''
classifier = Sequential()

# Adding the input layer and the first hidden layer

classifier.add(Dense(units = 50, kernel_initializer = 'uniform', activation = 'relu', input_dim = 14))


# Adding the second hidden layer

classifier.add(Dense(units = 30, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer

classifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'softmax'))


# Compiling the ANN

classifier.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

classifier.fit(x_train, y_train, batch_size = 50, epochs = 30)
'''

Epoch 1/30
652/652 [==============================] - 3s 5ms/step - loss: 382.6369 - accuracy: 0.1945
Epoch 2/30
652/652 [==============================] - 3s 4ms/step - loss: 2.7431 - accuracy: 0.2647
Epoch 3/30
652/652 [==============================] - 3s 4ms/step - loss: 2.2268 - accuracy: 0.2880
Epoch 4/30
652/652 [==============================] - 3s 4ms/step - loss: 2.1824 - accuracy: 0.2866
Epoch 5/30
652/652 [==============================] - 3s 4ms/step - loss: 2.0502 - accuracy: 0.3278
Epoch 6/30
652/652 [==============================] - 3s 5ms/step - loss: 2.0012 - accuracy: 0.3401
Epoch 7/30
652/652 [==============================] - 3s 4ms/step - loss: 2.1020 - accuracy: 0.3263
Epoch 8/30
652/652 [==============================] - 3s 4ms/step - loss: 2.0680 - accuracy: 0.3293
Epoch 9/30
652/652 [==============================] - 3s 4ms/step - loss: 1.9638 - accuracy: 0.3407
Epoch 10/30
652/652 [==============================] - 3s 4ms/step - loss: 1.9224 - accuracy: 0.35

"\nclassifier = Sequential()\n\n# Adding the input layer and the first hidden layer\n\nclassifier.add(Dense(units = 50, kernel_initializer = 'uniform', activation = 'relu', input_dim = 14))\n\n\n# Adding the second hidden layer\n\nclassifier.add(Dense(units = 30, kernel_initializer = 'uniform', activation = 'relu'))\n\n# Adding the output layer\n\nclassifier.add(Dense(units = 16, kernel_initializer = 'uniform', activation = 'softmax'))\n\n\n# Compiling the ANN\n\nclassifier.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])\n\nclassifier.fit(x_train, y_train, batch_size = 50, epochs = 30)\n"

In [ ]:
  loss, accuracy = model.evaluate(x_train, y_train)
print("訓練資料集的準確度 = {:.4f}".format(accuracy))
loss, accuracy = model.evaluate(x_test, y_test)
print("測試資料集的準確度 = {:.4f}".format(accuracy))
print("_______")
print(train_test_split)

1018/1018 [==============================] - 3s 3ms/step - loss: 0.4176 - accuracy: 0.8449
訓練資料集的準確度 = 0.8449
509/509 [==============================] - 1s 3ms/step - loss: 0.3452 - accuracy: 0.9083
測試資料集的準確度 = 0.9083
_______
<function train_test_split at 0x7f1d3768a710>


In [ ]:
import numpy as np
import pandas as pd
import math
import scipy.stats as sci
from sklearn.model_selection import train_test_split
from sklearn import ensemble, metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

forest = ensemble.RandomForestClassifier(n_estimators=1000)
forest_fit = forest.fit(x_train, y_train)
test_y_predicted = forest.predict(x_test)
accuracy = metrics.accuracy_score(y_test, test_y_predicted)
C = confusion_matrix(y_test, test_y_predicted)
print("Score",forest.score(x_test, y_test))
print(accuracy)
print(C)
print(classification_report(y_test, test_y_predicted))

Score 0.9924451814999079
0.9924451814999079
[[ 455    0    0    0    0    0    1    0    0    0    0    0    0    0
     0    0]
 [   0  637    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   0    5  219    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   0    0    0   59    7   13    0    0    0    0    0    0    0    0
     0    0]
 [   1    0    0    0  155   19    1    0    0    0    0    0    0    0
     0    0]
 [   1    0    0    0    2  303    3    0    0    0    0    0    0    0
     0    0]
 [   3    0    0    0    0    1  238    0    0    0    0    0    0    0
     0    0]
 [   0    0    0    0    0    0    0  532    1    1    0    0    0    0
     0    0]
 [   0    0    0    0    0    0    0    0  679    0    0    0    0    0
     0    0]
 [   0    0    0    0    0    0    0    0    0 2670    0    0    0    0
     0    0]
 [   0    0    0    0    0    0    0    0    0    5  162    0    8    0
     6    0]
 [   0    0    0    0

In [ ]:
#@title
'''NO'''
dataset = df.replace('?', np.nan)
dataset[pd.isnull(df).any(axis=1)].shape

In [ ]:
#@title
'''NO'''
df.dropna(inplace=True)
df.shape

In [ ]:
#@title
'''NO'''
df.drop('educational-num', axis=1, inplace=True)

In [ ]:
#@title
'''NO'''
categorical_columns = ['workclass','income','marital-status','occupation','relationship','gender','native-country','race']
label_column = ['education']

In [ ]:
#@title
'''NO'''
def show_unique_values(columns):
  for column in columns:
    uniq = df[column].unique().tolist()
    print(column+ " has "+ str(len(uniq)) +" values" + " : " + str(uniq))
show_unique_values(categorical_columns)
show_unique_values(label_column)

In [ ]:
#@title
'''NO'''
def convert_to_int(columns):
  for column in columns:
    unique_values = df[column].unique().tolist()
    dic = {}
    for indx, val in enumerate(unique_values):
      dic[val]=indx
    df[column] = df[column].map(dic).astype(int)
    print(column + " done!")
convert_to_int(label_column)
convert_to_int(categorical_columns)
show_unique_values(label_column)



In [ ]:
#@title
'''NO'''
def convert_to_onehot(data,columns):
  dummies = pd.get_dummies(data[columns])
  data = data.drop(columns, axis=1)
  data = pd.concat([data, dummies], axis=1)
  return data

df = convert_to_onehot(df,categorical_columns)


In [ ]:
#@title
'''NO'''
df.head()

In [ ]:
#@title
'''NO'''
normalize_columns = ['age', 'fnlwgt', 'capital-gain','capital-loss','hours-per-week']






def show_values(columns):
  for column in columns:
    max_val = df[column].max()
    min_val = df[column].min()
    mean_val = df[column].mean()
    var_val = df[column].var()
    print(column +': values=['+str(min_val)+','+str(max_val)+'] , mean='+str(mean_val)+' , var='+str(var_val))

show_values(normalize_columns)


In [ ]:
#@title
'''NO'''
df_1 = df

def normalize(columns):
  scaler = preprocessing.StandardScaler()
  df[columns] = scaler.fit_transform(df[columns])
normalize(normalize_columns)
show_values(normalize_columns)

In [ ]:
#@title
'''NO'''
df.head()

In [ ]:
#@title
'''NO'''
from sklearn.model_selection import train_test_split

x_data = df.drop('education',axis=1)
y_labels = df['education']
'''
X_train, X_test, y_train, y_test = train_test_split(x_data, y_labels, test_size=0.2,shuffle=True)
# X_train, X_valid, y_train, y_valid = train_test_split(X_train_full,y_train_full,test_size=0.2,shuffle=True)
'''

train_data, test_data, train_target, test_target = train_test_split(x_data, y_labels, train_size=0.8, test_size = 0.2) 

print(train_data,test_data,train_target,test_target)

In [ ]:
#@title
'''NO'''
from keras import backend as K
def f1(y_true, y_pred):
    def recall(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

    def precision(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision
        
    precision = precision(y_true, y_pred)
    recall = recall(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [ ]:
#@title
'''NO'''
keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)
#print(train_data.shape[1:])

In [ ]:
#@title
'''NO'''
import numpy as np
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
import numpy as np
import keras
from keras.utils import np_utils
from tensorflow.python.keras import regularizers
import matplotlib.pyplot as plt



model = Sequential()
model.add(Dense(16, activation="relu"))
model.add(Dense(32, activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(204, activation="relu"))
model.add(Dense(16, activation= 'softmax'))
# 編譯模型
model.compile(loss='sparse_categorical_crossentropy', optimizer="adam",
metrics=["accuracy"])


model.fit(train_data, train_target,
epochs=10,
batch_size=10
score = model.evaluate(test_data, test_target,batch_size=10)
model.summary()